### ISSUE TITLE
studio flags

### ISSUE THREAD

**Issue by MartijnKaijser** [ccMatrix/StudioLogos#1]
I also collected some flags that i found over time.
Perhaps sync them
https://github.com/XBMC-Addons/media.icons.collection

I've remove all bad named duplicates (which are still there in your git).
The flags that have the ?  in the names are not utf-8 filenames.

**Comment by ccMatrix** [comment]
What exactly do you have in mind? Copying flags back and forth and keeping both repositories in sync seems like a lot of work. If I understand your project correctly users or skins would install your addon and can then use all images instead of every skin providing its own copy. I really love that idea and I think the best course of action would be for me to just fork your repo and copy over all the icons into the studios folder then create a pull request so you can get the files upstream. the studiologos repo would essentially be dead then.

**Comment by MartijnKaijser** [comment]
I'm also an XBMC team member and what will be possible in post-Eden is that there will be a new category for media packs (like icons). So the flags can be updated separate from the skins just like normal add-ons.
We already tried that out and it worked pretty well.
So currently it's just the skinners that will still have to pull all the logos themselves.

I'm also admin at http://fanart.tv and we have been thinking about a subsection for logos. Only not sure yet on how that should be done. It already has some great artists contributing so missing logos would be created a lot faster i think.
I am open for suggestions of course and I would hate doing double work (like you probably) :)

**Comment by MartijnKaijser** [comment]
I solved the problem partially for record labels.
These are now hosted on http://fanart.tv and moderated to maintain quality. -> http://fanart.tv/music-fanart/
You can search for a record label by entering it in the search box.
We follow the MusicBrainz listing of record labels to make sure they are unique and well named.
I will make a script that will update a repo so we have the latest and best ones available for the skins.
Current options are "white" and "color" record labels

In future studio logos will be added there as well (i hope).
